blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/byearlybird/starling-server/discussions
    about: For questions and discussions, please use GitHub Discussions
  - name: Security Vulnerability
    url: https://github.com/byearlybird/starling-server/security/advisories/new
    about: Please report security vulnerabilities privately
